Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false