name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.99.0
        with:
          ruby-version: 3.1
          
      - name: Install dependencies
        run: bundle install
        
      - name: Run tests
        run: bundle exec rspec
        
      - name: Push to Workato
        env:
          WORKATO_API_EMAIL: ${{ secrets.WORKATO_API_EMAIL }}
          WORKATO_API_TOKEN: ${{ secrets.WORKATO_API_TOKEN }}
        run: workato push -n ${{ join( '"', github.event.head_commit.message, '"' ) }}
